# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine bump2version
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Bump version
      run: |
        sed "s/version.*/version='$(curl -Lsk https://pypi.org/pypi/github-utils-api/json | jq -r .info.version)',/" setup.py > setup.py2
        mv setup.py2 setup.py
        cat setup.py
        echo $(grep 'version=' setup.py   | awk -v FS='"' '{print $2}')
        bump2version --current-version $(grep 'version=' setup.py   | awk -v FS='"' '{print $2}') minor setup.py
    - name: Generating Artifacts
      run: |
        python setup.py sdist bdist_wheel
    - name: pypi-publish
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        # PyPI user
        #user: # optional, default is __token__
        # Password for your PyPI user or an access token
        password: ${{ secrets.PYPI_API_TOKEN }}
        # The repository URL to use
        #repository_url: # optional
        # The target directory for distribution
        #packages_dir: # optional, default is dist
        # Check metadata before uploading
        #verify_metadata: # optional, default is true
        # Do not fail if a Python package distribution exists in the target package index
        #skip_existing: # optional
        # Show verbose output.
        #verbose: # optional
        # Show hash values of files to be uploaded
        #print_hash: # optional
      if: github.event_name != 'pull_request'
